import { Injectable } from '@angular/core';

import { Weapon } from './weapons/weapon';
import { WeaponFilterData } from './weapons/filter/weapon-filter-data';

@Injectable()
export class ItemService {

  public getWeaponList(): Array<any> {
    return data;
  }

  public getWeaponById(id: string): any {
    return this.getWeaponsByIds([id])[0];
  }

  public getWeaponsByIds(ids: Array<string>): Array<any> {
    return data.filter((d) => ids.indexOf(d.name) > -1);
  }

  public getWeaponFilterData(): WeaponFilterData {
    let result: WeaponFilterData = new WeaponFilterData();

    for (let weapon of data) {
      // skill
      if (result.skills.indexOf(weapon.skill) == -1) {
        result.skills.push(weapon.skill);
      }

      // encumbrance
      if (result.encumbrances.indexOf(weapon.encumbrance) == -1) {
        result.encumbrances.push(weapon.encumbrance);
      }

      // range
      if (result.ranges.indexOf(weapon.range) == -1) {
        result.ranges.push(weapon.range);
      }

      // hard points
      if (result.hardPoints.indexOf(weapon.hardPoints) == -1) {
        result.hardPoints.push(weapon.hardPoints);
      }

      // Price
      let workingPrice: number;

      if(weapon.price.toString().indexOf('R') > -1) {
        workingPrice = parseInt(weapon.price.toString().substr(1));
      }
      else {
        workingPrice = <number>weapon.price;
      }

      if(result.maxPrice < workingPrice) {
        result.maxPrice = workingPrice;
      }
    }

    result.encumbrances.sort((a, b) => a < b ? -1 : a == b ? 0 : 1);
    result.hardPoints.sort((a, b) => a < b ? -1 : a == b ? 0 : 1);

    return result;
  }
}

let data = [
  {
    "type": "Energy Weapon",
    "name": "I 2 Defender",
    "source": "FH",
    "skill": "Light",
    "damage": 5,
    "critical": 5,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 25,
    "rarity": 4,
    "special": "Inferior, Limited Ammo 2",
    "features": "+2 setback die to Perception and Computers checks to find this weapon on person. Can not reload"
  },
  {
    "type": "Energy Weapon",
    "name": "Energy Slingshot",
    "source": "NP",
    "skill": "Light",
    "damage": 3,
    "critical": null,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 40,
    "rarity": 4,
    "special": "Disorient 2, Stun Setting",
    "features": "disorient triggered with 1 instead of 2 Advantage"
  },
  {
    "type": "Energy Weapon",
    "name": "CDEF Pistol",
    "source": "SF",
    "skill": "Light",
    "damage": 5,
    "critical": 4,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 150,
    "rarity": 4,
    "special": "Inferior, Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Holdout Blaster",
    "source": "Cores",
    "skill": "Light",
    "damage": 5,
    "critical": 4,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 200,
    "rarity": 4,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Spukami Pocket Blaster Pistol",
    "source": "SF",
    "skill": "Light",
    "damage": 5,
    "critical": 3,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 200,
    "rarity": 2,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Ion Blaster",
    "source": "Cores",
    "skill": "Light",
    "damage": 10,
    "critical": 5,
    "range": "Short",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 250,
    "rarity": 3,
    "special": "Disorient 5, Ion",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Model Q4 Quickfire",
    "source": "FH",
    "skill": "Light",
    "damage": 5,
    "critical": 3,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 250,
    "rarity": 4,
    "special": "Stun Setting",
    "features": "+1 setback die to Perception and Computers checks to find this weapon on person. Can not reload"
  },
  {
    "type": "Energy Weapon",
    "name": "Mon Calamari Battle Baton",
    "source": "SR",
    "skill": "Light",
    "damage": 5,
    "critical": 4,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 250,
    "rarity": 6,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Multi-Goo Gun",
    "source": "SM",
    "skill": "Light",
    "damage": 2,
    "critical": null,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 1,
    "price": 250,
    "rarity": 1,
    "special": "Disorient 1, Ensnare 4, Knockdown",
    "features": "+1 Adv. To repair draids, and vehicles; 2 Threat or 1 Despair to run out of ammo"
  },
  {
    "type": "Energy Weapon",
    "name": "Light Blaster Pistol",
    "source": "Cores",
    "skill": "Light",
    "damage": 5,
    "critical": 4,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 2,
    "price": 300,
    "rarity": 4,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Czerka Arms 411 Holdout Blaster",
    "source": "FC",
    "skill": "Light",
    "damage": 4,
    "critical": 4,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": "R 350",
    "rarity": 5,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "TT24 Holdout Blaster",
    "source": "SS",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 350,
    "rarity": 6,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Blaster Pistol",
    "source": "Cores",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 3,
    "price": 400,
    "rarity": 4,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Variable Holdout Blaster",
    "source": "SR",
    "skill": "Light",
    "damage": "1-7",
    "critical": 4,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 400,
    "rarity": 7,
    "special": "Limited Ammo 15 (1-7 used per shot, shooter selects)",
    "features": "+1 setback die to Perception and Computers checks to find this weapon on person."
  },
  {
    "type": "Energy Weapon",
    "name": "ELG-3A",
    "source": "DA",
    "skill": "Light",
    "damage": 6,
    "critical": 4,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 400,
    "rarity": 5,
    "special": "Stun Setting",
    "features": "+2 setback die to Perception and Computers checks to find this weapon on person."
  },
  {
    "type": "Energy Weapon",
    "name": "Czerka Arms A95 Stingbeam",
    "source": "FC",
    "skill": "Light",
    "damage": 5,
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 400,
    "rarity": 5,
    "special": "Stun Setting, Vicious 1",
    "features": "+2 setback die to Perception and Computers checks to find this weapon on person."
  },
  {
    "type": "Energy Weapon",
    "name": "Liquidsilver L7 Light Blaster Pistol",
    "source": "FC",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 425,
    "rarity": 4,
    "special": "Stun Setting",
    "features": "+2 setback die to Perception and Computers checks to find this weapon stashed on a starship."
  },
  {
    "type": "Energy Weapon",
    "name": "Blastech DL-19C Blaster Pistol",
    "source": "SM",
    "skill": "Light",
    "damage": 5,
    "critical": 4,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 4,
    "price": 450,
    "rarity": 4,
    "special": "Stun Setting",
    "features": "w/Jurry Rigged Talent may apply 1 additional option"
  },
  {
    "type": "Energy Weapon",
    "name": "Merr-Sonn Model 53 Quicktrigger",
    "source": "FC",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 4,
    "price": 450,
    "rarity": 4,
    "special": "Stun Setting",
    "features": "Reduce difficulty of Mechanics checks to repair gun or attachments by 1"
  },
  {
    "type": "Energy Weapon",
    "name": "HL-27 Light Blaster Pistol",
    "source": "SF",
    "skill": "Light",
    "damage": 5,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 2,
    "price": 450,
    "rarity": 4,
    "special": "Accurate 1, Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "XL-2 Flashfire",
    "source": "SF",
    "skill": "Light",
    "damage": 5,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 3,
    "price": 450,
    "rarity": 5,
    "special": "Disorient 1, Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Militairy Holdout Blaster",
    "source": "DA",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 500,
    "rarity": 5,
    "special": "Stun Setting",
    "features": "+1 setback die to Perception and Computers checks to find this weapon on person. 3 Threats to run out of ammo"
  },
  {
    "type": "Energy Weapon",
    "name": "Model 44 Blaster Pistol",
    "source": "DC",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 4,
    "price": 500,
    "rarity": 4,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Model 80 Blaster Pistol",
    "source": "DC",
    "skill": "Light",
    "damage": 6,
    "critical": 2,
    "range": "Medium",
    "encumbrance": 2,
    "hardPoints": 3,
    "price": 550,
    "rarity": 5,
    "special": "Stun Setting",
    "features": "Time taken to access this weapon can not be reduced."
  },
  {
    "type": "Energy Weapon",
    "name": "Relby-K23 Blaster Pistol",
    "source": "SS",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 600,
    "rarity": 6,
    "special": "Pierce 2, Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "CR-2 Heavy Blaster Pistol",
    "source": "SF",
    "skill": "Light",
    "damage": 7,
    "critical": 4,
    "range": "Medium",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": 600,
    "rarity": 5,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "KO-2 Heavy Stun Pistol",
    "source": "KP",
    "skill": "Light",
    "damage": 8,
    "critical": null,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 3,
    "price": 650,
    "rarity": 5,
    "special": "Stun Damage",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Defender Sporting Blaster Pistol",
    "source": "DA",
    "skill": "Light",
    "damage": 5,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 650,
    "rarity": 6,
    "special": "Stun Settint, Accurate 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Heavy Blaster Pistol",
    "source": "Cores",
    "skill": "Light",
    "damage": 7,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 2,
    "hardPoints": 5,
    "price": 700,
    "rarity": 6,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "IR-5 Intimidator",
    "source": "DC",
    "skill": "Light",
    "damage": 5,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": "R 750",
    "rarity": 6,
    "special": "Auto-Fire, Inaccurate 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Dueling Pistol",
    "source": "SF",
    "skill": "Light",
    "damage": 9,
    "critical": 2,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": 750,
    "rarity": 5,
    "special": "Accurate 1, Limited Ammo 1, Pierce 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Greff-Timms ATA Pulse-Wave Blaster",
    "source": "LN",
    "skill": "Light",
    "damage": 5,
    "critical": 3,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": "R 750",
    "rarity": 6,
    "special": "Vicious 3",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Droid Disruptor",
    "source": "SR",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 1,
    "price": 800,
    "rarity": 7,
    "special": "Vicious 3 (to drois only),",
    "features": "Organics only receive 2 strain (no damage)"
  },
  {
    "type": "Energy Weapon",
    "name": "DL-7H Heavy Blaster Pistol",
    "source": "DC",
    "skill": "Light",
    "damage": 8,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": "R 850",
    "rarity": 6,
    "special": "Stun Setting",
    "features": "2 Threats to run out of ammo"
  },
  {
    "type": "Energy Weapon",
    "name": "SSB-1 Static Pistol",
    "source": null,
    "skill": "Light",
    "damage": 2,
    "critical": 4,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 1,
    "price": 850,
    "rarity": 7,
    "special": "Disorient 1, Stun 8",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Rivet Gun",
    "source": "SM",
    "skill": "Light",
    "damage": 4,
    "critical": 5,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 1,
    "price": 900,
    "rarity": 1,
    "special": "Ensnare 1, Inaccurate 2, Limited Ammo 1",
    "features": "Reduce Mechanics checks to repair Critical Hits on vehicles by 1"
  },
  {
    "type": "Energy Weapon",
    "name": "Renegade",
    "source": "SR",
    "skill": "Light",
    "damage": 8,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 950,
    "rarity": 4,
    "special": "Inaccurate 1, Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "X-30 Lancer",
    "source": "EU",
    "skill": "Light",
    "damage": 5,
    "critical": 4,
    "range": "Long",
    "encumbrance": 1,
    "hardPoints": 3,
    "price": 1000,
    "rarity": 5,
    "special": "Accurate 1, Pierce 2",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "C-10 Dragoneye Reaper",
    "source": "FC",
    "skill": "Light",
    "damage": 8,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 1000,
    "rarity": 7,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Boonta Blaster",
    "source": "LN",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 1000,
    "rarity": 8,
    "special": "Stun Setting",
    "features": "+1 setback die to find on a person. -1 setback die to Deception to explain as an ornament or non-threatening"
  },
  {
    "type": "Energy Weapon",
    "name": "SE-14R Light Repeating Blaster",
    "source": "DC",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 2,
    "hardPoints": 3,
    "price": "R 1000",
    "rarity": 6,
    "special": "Auto Fire, Stun Setting",
    "features": "3 Threats to run out of ammo"
  },
  {
    "type": "Energy Weapon",
    "name": "Felebreck Droid Disabler",
    "source": "FC",
    "skill": "Light",
    "damage": 12,
    "critical": 3,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 1050,
    "rarity": 5,
    "special": "Concussive 1, Ion, Limited Ammo 3",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "H-7 Equalizer",
    "source": "SF",
    "skill": "Light",
    "damage": 7,
    "critical": 2,
    "range": "Medium",
    "encumbrance": 2,
    "hardPoints": 3,
    "price": 1200,
    "rarity": 8,
    "special": "Stun Setting, Superior",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Security S-5 Heavy Blaster",
    "source": "KP",
    "skill": "Light",
    "damage": 7,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 3,
    "hardPoints": 1,
    "price": 1250,
    "rarity": 7,
    "special": "Stun Setting",
    "features": "Average Light check to use grappling hook. Average Athletics to carry someone with you."
  },
  {
    "type": "Energy Weapon",
    "name": "HH 50 Heavy Blaster Pistol",
    "source": "ST",
    "skill": "Light",
    "damage": 7,
    "critical": 3,
    "range": "Short",
    "encumbrance": 3,
    "hardPoints": 2,
    "price": 1300,
    "rarity": 7,
    "special": "Linked 1, Stun Setting, Vicious 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Site-145 Replica Blaster Pistol",
    "source": "KP",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": "R 1750",
    "rarity": 8,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "DR-45 Dragoon",
    "source": "ST",
    "skill": "Light",
    "damage": 8,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 3,
    "price": 1900,
    "rarity": 6,
    "special": "Accurate 1, Stun Setting",
    "features": "Can be switched to a carbine (use Ranged-Heavy Skill instead)"
  },
  {
    "type": "Energy Weapon",
    "name": "Disruptor Pistol",
    "source": "Cores",
    "skill": "Light",
    "damage": 10,
    "critical": 2,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": "R 3000",
    "rarity": 6,
    "special": "Vicious 4",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Raider Arms Model-1 Nova Viper",
    "source": "FC",
    "skill": "Light",
    "damage": 7,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": 4500,
    "rarity": 9,
    "special": "Accurate 2, Pierce 2, Stun Setting",
    "features": "Increase Mechanics checks to repair or mod by 1"
  },
  {
    "type": "Energy Weapon",
    "name": "Repulsor Gun",
    "source": "SM",
    "skill": "Heavy",
    "damage": 3,
    "critical": 5,
    "range": "Short",
    "encumbrance": 5,
    "hardPoints": 0,
    "price": 200,
    "rarity": 3,
    "special": "Knockdown",
    "features": "1 Despair = backfire: user knocked prone, and disoriented 2 rounds"
  },
  {
    "type": "Energy Weapon",
    "name": "Ion Thruster Gun",
    "source": "SM",
    "skill": "Heavy",
    "damage": 5,
    "critical": 6,
    "range": "Short",
    "encumbrance": 8,
    "hardPoints": 0,
    "price": 300,
    "rarity": 2,
    "special": "Soncussive 1, Cumbersome 5, Ion, Prepare 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "E5 Blaster Carbine",
    "source": "ST",
    "skill": "Heavy",
    "damage": 9,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 3,
    "hardPoints": 4,
    "price": 550,
    "rarity": 3,
    "special": "Stun Setting, Inaccurate 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "SKZ Sporting Blaster",
    "source": "SF",
    "skill": "Heavy",
    "damage": 8,
    "critical": 4,
    "range": "Long",
    "encumbrance": 3,
    "hardPoints": 4,
    "price": 600,
    "rarity": 4,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Blaster Carbine",
    "source": "Cores",
    "skill": "Heavy",
    "damage": 9,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 2,
    "hardPoints": 4,
    "price": 850,
    "rarity": 5,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Weequay Blaster Lance",
    "source": "LN",
    "skill": "Heavy",
    "damage": 8,
    "critical": 3,
    "range": "Extreme",
    "encumbrance": 5,
    "hardPoints": 2,
    "price": 850,
    "rarity": 6,
    "special": "Accurate 1, Cumbersome 2",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "ACP Array Gun",
    "source": "DC",
    "skill": "Heavy",
    "damage": 6,
    "critical": 3,
    "range": "Short",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 890,
    "rarity": 6,
    "special": "Blast 5, Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Blaster Rifle",
    "source": "Cores",
    "skill": "Heavy",
    "damage": 9,
    "critical": 3,
    "range": "Long",
    "encumbrance": 4,
    "hardPoints": 4,
    "price": 900,
    "rarity": 5,
    "special": "Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Herloss HBt-4 Hunting Blaster",
    "source": "FC",
    "skill": "Heavy",
    "damage": 10,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 5,
    "hardPoints": 2,
    "price": 900,
    "rarity": 6,
    "special": "Cumbersome 2, Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Crorondexx VES-700 Pulse Rifle",
    "source": "FC",
    "skill": "Heavy",
    "damage": 8,
    "critical": 5,
    "range": "Medium",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 950,
    "rarity": 6,
    "special": "Blast 6, Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "DDC-MR6 Modular Rifle",
    "source": "SM",
    "skill": "Heavy",
    "damage": 7,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 3,
    "hardPoints": 6,
    "price": 1000,
    "rarity": 6,
    "special": "Stun Setting",
    "features": "Average Mechanics Check ro add or remove attachment as an action"
  },
  {
    "type": "Energy Weapon",
    "name": "Flame Projector",
    "source": null,
    "skill": "Heavy",
    "damage": 8,
    "critical": 2,
    "range": "Short",
    "encumbrance": 6,
    "hardPoints": 2,
    "price": 1000,
    "rarity": 6,
    "special": "Burn 3, Blast 8",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "ACP Repeater Gun",
    "source": "LN",
    "skill": "Heavy",
    "damage": 7,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 3,
    "hardPoints": 1,
    "price": 1000,
    "rarity": 6,
    "special": "Auto Fire, Stun Setting",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "OK-98 Blaster Carbine",
    "source": "DC",
    "skill": "Heavy",
    "damage": 9,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 4,
    "hardPoints": 3,
    "price": 1100,
    "rarity": 5,
    "special": "Stun Setting",
    "features": "Ignore first Despair for out of ammo, OR modify (easy check) for +2 damage but Despair = weapon explodes"
  },
  {
    "type": "Energy Weapon",
    "name": "Sonic Rifle",
    "source": "FH",
    "skill": "Heavy",
    "damage": 8,
    "critical": 6,
    "range": "Long",
    "encumbrance": 4,
    "hardPoints": 3,
    "price": 1200,
    "rarity": 6,
    "special": "Concussive 1, Slow-Firing 1, Stun Damage",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Bowcaster",
    "source": "EEC",
    "skill": "Heavy",
    "damage": 10,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 5,
    "hardPoints": 2,
    "price": 1250,
    "rarity": 7,
    "special": "Cumbersome 3, Knockdown",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Mon Calamari Spear Blaster",
    "source": "SR",
    "skill": "Heavy",
    "damage": 8,
    "critical": 3,
    "range": "Long",
    "encumbrance": 5,
    "hardPoints": 4,
    "price": 1350,
    "rarity": 5,
    "special": "Stun Setting",
    "features": "Can be used as a spear as well (see Melee weapons)"
  },
  {
    "type": "Energy Weapon",
    "name": "DLS-12 Heavy Blaster Carbine",
    "source": "KP",
    "skill": "Heavy",
    "damage": 10,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 4,
    "hardPoints": 3,
    "price": 1350,
    "rarity": 7,
    "special": "Auto Fire, Cumbersome 3",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Heavy Blaster Rifle",
    "source": "Cores",
    "skill": "Heavy",
    "damage": 10,
    "critical": 3,
    "range": "Long",
    "encumbrance": 6,
    "hardPoints": 4,
    "price": 1500,
    "rarity": 6,
    "special": "Auto-fire, Cumbersome 3",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "D29 Repulsor Rifle",
    "source": "LN",
    "skill": "Heavy",
    "damage": 8,
    "critical": 4,
    "range": "Medium",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 1550,
    "rarity": 7,
    "special": "Disorient 3, Knockdown, Stun Damage",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Bola Carbine",
    "source": "SR",
    "skill": "Heavy",
    "damage": 8,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 1600,
    "rarity": 6,
    "special": "Ensnare 1, Accurate 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "BlasTech M-300 Hunting Blaster",
    "source": "SS",
    "skill": "Heavy",
    "damage": 8,
    "critical": 3,
    "range": "Extreme",
    "encumbrance": 4,
    "hardPoints": 1,
    "price": 1600,
    "rarity": 6,
    "special": "Accurate 1, Cumbersome 2, Pierce 2, Stun Damage",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "DH-X Heavy Blaster Rifle",
    "source": "DC",
    "skill": "Heavy",
    "damage": 10,
    "critical": 3,
    "range": "Long",
    "encumbrance": 7,
    "hardPoints": 4,
    "price": 1900,
    "rarity": 6,
    "special": "Cumbersome 3, Pierce 2",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Light Repeating Blaster",
    "source": "Cores",
    "skill": "Heavy",
    "damage": 11,
    "critical": 5,
    "range": "Long",
    "encumbrance": 7,
    "hardPoints": 4,
    "price": "R 2250",
    "rarity": 7,
    "special": "Auto-Fire, Cumbersome 4, Peirce 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "LBR-9 Stun Rifle",
    "source": "EU",
    "skill": "Heavy",
    "damage": 10,
    "critical": null,
    "range": "Long",
    "encumbrance": 6,
    "hardPoints": 4,
    "price": 2800,
    "rarity": 4,
    "special": "Disorient 2, Stun Damage",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Nightstalker Energy Bow",
    "source": null,
    "skill": "Heavy",
    "damage": 8,
    "critical": 2,
    "range": "Medium",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": "R 2800",
    "rarity": 8,
    "special": "Pierce 4, Unwieldy 3, Vicious 2",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Corellian Arms CR-8 Takedown Rifle",
    "source": null,
    "skill": "Heavy",
    "damage": 9,
    "critical": 3,
    "range": "Extreme",
    "encumbrance": 4,
    "hardPoints": 1,
    "price": "R 3250",
    "rarity": 7,
    "special": "Accurate 2, Prepare 2, Pierce 2, Slow-Firing 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "E-11s",
    "source": "EU",
    "skill": "Heavy",
    "damage": 10,
    "critical": 3,
    "range": "Extreme",
    "encumbrance": 6,
    "hardPoints": 3,
    "price": "R 3500",
    "rarity": 7,
    "special": "Disorient 2, Stun Damage",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Disruptor Rifle",
    "source": "Cores",
    "skill": "Heavy",
    "damage": 10,
    "critical": 2,
    "range": "Long",
    "encumbrance": 5,
    "hardPoints": 4,
    "price": "R 5000",
    "rarity": 6,
    "special": "Cumbersome  2, Vicious 5",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "VX Sidewinder Repeating Blaster",
    "source": "DC",
    "skill": "Gunnery",
    "damage": 12,
    "critical": 3,
    "range": "Long",
    "encumbrance": 8,
    "hardPoints": 4,
    "price": "R 3350",
    "rarity": 7,
    "special": "Auto-Fire, Cumbersome 5, Pierce 1, Vicious 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "Heavy Repeating Blaster",
    "source": "Cores",
    "skill": "Gunnery",
    "damage": 15,
    "critical": 2,
    "range": "Long",
    "encumbrance": 9,
    "hardPoints": 4,
    "price": "R 6000",
    "rarity": 8,
    "special": "Auto-Fire, Cumbersome 5, Pierce 2, Vicious 1",
    "features": null
  },
  {
    "type": "Energy Weapon",
    "name": "HOB Heavy Repeating Blaster",
    "source": "DC",
    "skill": "Gunnery",
    "damage": 15,
    "critical": 3,
    "range": "Extreme",
    "encumbrance": 10,
    "hardPoints": 4,
    "price": "R 6500",
    "rarity": 8,
    "special": "Auto-Fire, Cumbersome 6, Pierce 2, Vicious 1",
    "features": "+1 setback die to Mechanics checks to repair"
  },
  {
    "type": "Slug Weapon",
    "name": "Slugthrower Pistol",
    "source": "Cores",
    "skill": "Light",
    "damage": 4,
    "critical": 5,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 100,
    "rarity": 3,
    "special": null,
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "ASP-9 Autopistol",
    "source": "SF",
    "skill": "Light",
    "damage": 4,
    "critical": 5,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 150,
    "rarity": 4,
    "special": "Auto-Fire",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Fiver Pistol",
    "source": "DC",
    "skill": "Light",
    "damage": 5,
    "critical": 4,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 1,
    "price": 200,
    "rarity": 4,
    "special": "Inacurate, Limited Ammo 5",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Stealth-2VX Palm Shooter",
    "source": "LN",
    "skill": "Light",
    "damage": 1,
    "critical": 5,
    "range": "Short",
    "encumbrance": 0,
    "hardPoints": 0,
    "price": 300,
    "rarity": 5,
    "special": "Limited Ammo 3",
    "features": "+2 setback die to Perception checks to find this weapon on person."
  },
  {
    "type": "Slug Weapon",
    "name": "KD-30 Dissuader",
    "source": "LN",
    "skill": "Light",
    "damage": 4,
    "critical": 5,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": 350,
    "rarity": 6,
    "special": "Pierce 2, Vicious 1",
    "features": "on hit 1 wound at the beginning of each of the next 2 rounds, ignoring all soak"
  },
  {
    "type": "Slug Weapon",
    "name": "FWG-5 Flechette Pistol",
    "source": "FC",
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 2,
    "price": "R 825",
    "rarity": 7,
    "special": "Guided 3, Limited Ammo 3",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Verpine Shatter Pistol",
    "source": "SR",
    "skill": "Light",
    "damage": 8,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 2,
    "price": "15,000",
    "rarity": 8,
    "special": "Knockdown, Pierce 2",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Slugthrower Rifle",
    "source": "Cores",
    "skill": "Heavy",
    "damage": 7,
    "critical": 5,
    "range": "Medium",
    "encumbrance": 5,
    "hardPoints": 1,
    "price": 250,
    "rarity": 3,
    "special": "Cumbersome 2",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Assault Carbine",
    "source": "DC",
    "skill": "Heavy",
    "damage": 6,
    "critical": 5,
    "range": "Short",
    "encumbrance": 4,
    "hardPoints": 1,
    "price": 250,
    "rarity": 4,
    "special": "Auto-Fire, Inaccurate 1",
    "features": "2 Threats to run out of ammo"
  },
  {
    "type": "Slug Weapon",
    "name": "Czerka Arms Model 57 'Homesteader' Hunting Rifle",
    "source": "SS",
    "skill": "Heavy",
    "damage": 7,
    "critical": 5,
    "range": "Long",
    "encumbrance": 5,
    "hardPoints": 4,
    "price": 500,
    "rarity": 6,
    "special": "Accurate 1, Cumbersome 2",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Adostic Arms 8-Gauge Scatter Gun",
    "source": "FC",
    "skill": "Heavy",
    "damage": 7,
    "critical": 6,
    "range": "Short",
    "encumbrance": 3,
    "hardPoints": 2,
    "price": 550,
    "rarity": 4,
    "special": "Blast 3, Knockdown",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Vodran Hunting Rifle",
    "source": "LN",
    "skill": "Heavy",
    "damage": 7,
    "critical": 4,
    "range": "Long",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 800,
    "rarity": 7,
    "special": "Cumbersome 2",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "DF-D1 Duo-Flechette Rifle",
    "source": "SR",
    "skill": "Heavy",
    "damage": 9,
    "critical": 3,
    "range": "Short",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": "R 1000",
    "rarity": 5,
    "special": "Blast 4, Limited Ammo 5, Linked 1, Vicious 2",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Model 77 Air Rifle",
    "source": "EU",
    "skill": "Heavy",
    "damage": 6,
    "critical": null,
    "range": "Long",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 1100,
    "rarity": 6,
    "special": "Pierce 4, Stun Damage",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "KS-23 Hammer",
    "source": "EU",
    "skill": "Heavy",
    "damage": 8,
    "critical": 4,
    "range": "Short",
    "encumbrance": 5,
    "hardPoints": 4,
    "price": 1500,
    "rarity": 5,
    "special": "Blast 6, Knockdown",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Selonian Shard Shooter",
    "source": "SF",
    "skill": "Heavy",
    "damage": 5,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 1500,
    "rarity": 7,
    "special": "Auto-Fire, Pierce 1",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Mark V Sand Panther",
    "source": "SF",
    "skill": "Heavy",
    "damage": 7,
    "critical": 5,
    "range": "Long",
    "encumbrance": 5,
    "hardPoints": 2,
    "price": 1750,
    "rarity": 7,
    "special": "Accurate 1,  Cumbersome 2",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Model 38",
    "source": "EU",
    "skill": "Heavy",
    "damage": 8,
    "critical": 3,
    "range": "Extreme",
    "encumbrance": 5,
    "hardPoints": 4,
    "price": 3000,
    "rarity": 6,
    "special": "Accurate 2, Pierce 3",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Model 38 (w/Detonator Rounds",
    "source": "EU",
    "skill": "Heavy",
    "damage": 8,
    "critical": 3,
    "range": "Extreme",
    "encumbrance": 5,
    "hardPoints": 4,
    "price": 3000,
    "rarity": 6,
    "special": "Accurate 2, Blast 5, Knockdown",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Verpine Shatter Rifle",
    "source": "SR",
    "skill": "Heavy",
    "damage": 12,
    "critical": 3,
    "range": "Extreme",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": "30,000",
    "rarity": 8,
    "special": "Knockdown, Pierce 4",
    "features": null
  },
  {
    "type": "Slug Weapon",
    "name": "Verpine Heavy Shatter Rifle",
    "source": "SR",
    "skill": "Gunnery",
    "damage": 15,
    "critical": 2,
    "range": "Extreme",
    "encumbrance": 4,
    "hardPoints": 4,
    "price": "45,000",
    "rarity": 8,
    "special": "Accurate 2, Knockdown, Pierce 6",
    "features": null
  },
  {
    "type": "Other",
    "name": "Bola/Net",
    "source": null,
    "skill": "Light",
    "damage": 2,
    "critical": null,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 2,
    "price": 20,
    "rarity": 2,
    "special": "Ensnare 3, Knockdown, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Gungan Plasma Ball",
    "source": null,
    "skill": "Light",
    "damage": 5,
    "critical": 3,
    "range": "Short",
    "encumbrance": 0,
    "hardPoints": 0,
    "price": 20,
    "rarity": 7,
    "special": "Burn 1, Ion, Limited Ammo 1",
    "features": "Ammunition for Gungan Atlatl"
  },
  {
    "type": "Other",
    "name": "Frag Grenade",
    "source": null,
    "skill": "Light",
    "damage": 8,
    "critical": 4,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 50,
    "rarity": 5,
    "special": "Blast 6, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Poison Gas Grenade",
    "source": null,
    "skill": "Light",
    "damage": 0,
    "critical": 2,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 50,
    "rarity": 5,
    "special": "Blast 2, Limited Ammo 1",
    "features": "1 dose of neurotoxin anaseptic or other toxin; lingers for 2 rounds"
  },
  {
    "type": "Other",
    "name": "Ascian Throwing Dagger",
    "source": null,
    "skill": "Light",
    "damage": "BR +1",
    "critical": 2,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 65,
    "rarity": 7,
    "special": "Pierce 2, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Aurateran Boomerang",
    "source": null,
    "skill": "Light",
    "damage": 4,
    "critical": 5,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 65,
    "rarity": 6,
    "special": "Guided 1, Limited Ammo 1",
    "features": "Can be retrieved and used again; Advantage can be used on miss to return to hand"
  },
  {
    "type": "Other",
    "name": "Ion Grenade",
    "source": null,
    "skill": "Light",
    "damage": 10,
    "critical": 5,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 65,
    "rarity": 4,
    "special": "Blast 7, Disorient 5, Stun Damage (Droid Only), Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Stun Grenade",
    "source": null,
    "skill": "Light",
    "damage": 8,
    "critical": null,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 75,
    "rarity": 4,
    "special": "Disorient 3, Stun Damage, Blast 8, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "D-24 Inferno Grenade",
    "source": null,
    "skill": "Light",
    "damage": 8,
    "critical": 3,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": "R 75",
    "rarity": 5,
    "special": "Blast 6, Burn 2, Limited Ammo1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Mk. 4 Heavy Frag Grenade",
    "source": null,
    "skill": "Light",
    "damage": 9,
    "critical": 4,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": "R 75",
    "rarity": 5,
    "special": "Blast 7, Cumbersome 2, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Armor-Piercing Grenade",
    "source": null,
    "skill": "Light",
    "damage": 13,
    "critical": 3,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 100,
    "rarity": 6,
    "special": "Blast 4, Limited Ammo 1, Pierce 3",
    "features": null
  },
  {
    "type": "Other",
    "name": "Glop Grenade",
    "source": null,
    "skill": "Light",
    "damage": 0,
    "critical": null,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 100,
    "rarity": 6,
    "special": "Blast 0, Ensnare 3",
    "features": null
  },
  {
    "type": "Other",
    "name": "SoroSubb Wipe-3 Data-Purge Grenade",
    "source": null,
    "skill": "Light",
    "damage": 0,
    "critical": null,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 100,
    "rarity": 7,
    "special": "Limited Ammo 1",
    "features": "Computers lose all programming and data; Droids make Hard Res. Check or 1 strain per Fail. 1 Desp. Or 3 Threat can cause memory loss"
  },
  {
    "type": "Other",
    "name": "Gungan Atlatl",
    "source": null,
    "skill": "Light",
    "damage": 5,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": 100,
    "rarity": 7,
    "special": "Accurate 1, Burn 1, Ion, Limited Ammo 1",
    "features": "Must have Plasma Balls for Ammunition"
  },
  {
    "type": "Other",
    "name": "G-2 Concussion Grenade",
    "source": null,
    "skill": "Light",
    "damage": 10,
    "critical": 5,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": "R 100",
    "rarity": 5,
    "special": "Blast 8, Concussive 2, Disorient 5, Limited Ammo 1",
    "features": "Disorient all in Short Range, even if not damaged."
  },
  {
    "type": "Other",
    "name": "Knockout Grenade",
    "source": null,
    "skill": "Light",
    "damage": 12,
    "critical": null,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 120,
    "rarity": 5,
    "special": "Blast 10, Stun Damage, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Plasma Grenade",
    "source": null,
    "skill": "Light",
    "damage": 12,
    "critical": 3,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 125,
    "rarity": 6,
    "special": "Blast 10, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Merr-Sonn N-4 Noise Grenade",
    "source": null,
    "skill": "Light",
    "damage": 4,
    "critical": 6,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 150,
    "rarity": 5,
    "special": "Blast 4, Stun Damage, Concussive 1, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Goseia HIC Mercy",
    "source": null,
    "skill": "Light",
    "damage": 5,
    "critical": null,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 175,
    "rarity": 8,
    "special": "Blast 5, Stun Damage, Limited Ammo 1",
    "features": "If hit, make Hard Resillience check, disoriented 1 round per Threat and broken memory of encounter"
  },
  {
    "type": "Other",
    "name": "Bennkeyes Syndicate Knockout Mine",
    "source": null,
    "skill": "Light",
    "damage": 6,
    "critical": null,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 200,
    "rarity": 6,
    "special": "Stun Damage, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Voss Warspear (thrown)",
    "source": null,
    "skill": "Light",
    "damage": "BR+2",
    "critical": 4,
    "range": "Short",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 215,
    "rarity": 8,
    "special": "Defensive 2, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Spore/B Stun Grenade",
    "source": null,
    "skill": "Light",
    "damage": 6,
    "critical": 3,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 400,
    "rarity": 5,
    "special": "Blaast 6, Concussive 2, Limited Ammo 1, Stun Damage",
    "features": "First time hit, roll 1 Challenge Die, if Despair, 6 strain and begin suffocating (Hard Medicine check to stop)"
  },
  {
    "type": "Other",
    "name": "Gungan Electropole (thrown)",
    "source": null,
    "skill": "Light",
    "damage": "BR+2",
    "critical": 4,
    "range": "Short",
    "encumbrance": 3,
    "hardPoints": 2,
    "price": 450,
    "rarity": 5,
    "special": "Limited Ammo 1, Stun 3, Stun Setting",
    "features": null
  },
  {
    "type": "Other",
    "name": "Thermal Detonator",
    "source": null,
    "skill": "Light",
    "damage": 20,
    "critical": 2,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": "R 2000",
    "rarity": 8,
    "special": "Blast 15, Breach 1, Vicious 4, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Net Arrow",
    "source": null,
    "skill": "Heavy",
    "damage": 2,
    "critical": null,
    "range": "Medium",
    "encumbrance": 0,
    "hardPoints": 0,
    "price": 30,
    "rarity": 5,
    "special": "Ensnare 2, Limited Ammo 1",
    "features": "Ammunition for bow"
  },
  {
    "type": "Other",
    "name": "Explosive Tipped Arrows",
    "source": null,
    "skill": "Heavy",
    "damage": 6,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 0,
    "hardPoints": 0,
    "price": 50,
    "rarity": 6,
    "special": "Blast , Limited Ammo 1",
    "features": "Ammunition for bow"
  },
  {
    "type": "Other",
    "name": "Mini-Torpedo, Ink",
    "source": null,
    "skill": "Heavy",
    "damage": 2,
    "critical": null,
    "range": "Long",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 50,
    "rarity": 5,
    "special": "Blast 0, Disorient 4, Limited Ammo 1",
    "features": "Ammuntion for Mini-Torpedo Launcher; blocks line of sight and obscures vision for 4 rounds"
  },
  {
    "type": "Other",
    "name": "Incendiary Arrows",
    "source": null,
    "skill": "Heavy",
    "damage": 6,
    "critical": 5,
    "range": "Medium",
    "encumbrance": 0,
    "hardPoints": 0,
    "price": 60,
    "rarity": 5,
    "special": "Burn 2, Limited Ammo 1",
    "features": "Ammunition for bow"
  },
  {
    "type": "Other",
    "name": "Stun Arrows",
    "source": null,
    "skill": "Heavy",
    "damage": 6,
    "critical": null,
    "range": "Medium",
    "encumbrance": 0,
    "hardPoints": 0,
    "price": 60,
    "rarity": 6,
    "special": "Limited Ammo 1, Stun Damage",
    "features": "Ammunition for bow"
  },
  {
    "type": "Other",
    "name": "Mini-Torpedo, Net",
    "source": null,
    "skill": "Heavy",
    "damage": 0,
    "critical": null,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 100,
    "rarity": 5,
    "special": "Blast 0, Ensnare 6, Limited Ammo 1",
    "features": "Ammuntion for Mini-Torpedo Launcher"
  },
  {
    "type": "Other",
    "name": "Mini-Torpedo Anti-Personnel",
    "source": null,
    "skill": "Heavy",
    "damage": 8,
    "critical": 2,
    "range": "Long",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 100,
    "rarity": 5,
    "special": "Blast 6, Limited Ammo 2",
    "features": "Ammuntion for Mini-Torpedo Launcher"
  },
  {
    "type": "Other",
    "name": "Long Bow",
    "source": null,
    "skill": "Heavy",
    "damage": 5,
    "critical": 5,
    "range": "Long",
    "encumbrance": 5,
    "hardPoints": 1,
    "price": 120,
    "rarity": 4,
    "special": "Cumbersome 3, Limited Ammo 1, Pierce 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Mini-Torpedo, Armor Piercing",
    "source": null,
    "skill": "Heavy",
    "damage": 12,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 150,
    "rarity": 6,
    "special": "Blast 2, Limited Ammo 1, Pierce 4",
    "features": "Ammuntion for Mini-Torpedo Launcher"
  },
  {
    "type": "Other",
    "name": "Mini-Torpedo Ion",
    "source": null,
    "skill": "Heavy",
    "damage": 10,
    "critical": 2,
    "range": "Long",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 150,
    "rarity": 6,
    "special": "Blast 8, Ion, Limited Ammo 1",
    "features": "Ammuntion for Mini-Torpedo Launcher"
  },
  {
    "type": "Other",
    "name": "Styanax Lance",
    "source": null,
    "skill": "Heavy",
    "damage": 8,
    "critical": 5,
    "range": "Short",
    "encumbrance": 8,
    "hardPoints": 2,
    "price": 200,
    "rarity": 8,
    "special": "Cumbersome 4, Limited Ammo 1, Pierce 3, Vicious 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Corellian Compound Bow",
    "source": null,
    "skill": "Heavy",
    "damage": 5,
    "critical": 5,
    "range": "Medium",
    "encumbrance": 3,
    "hardPoints": 1,
    "price": 200,
    "rarity": 5,
    "special": "Cumbersome 3, Knockdown, Limited Ammo 1, Pierce 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Field Sports FS19 Compund Bow",
    "source": null,
    "skill": "Heavy",
    "damage": 5,
    "critical": 4,
    "range": "Medium",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 500,
    "rarity": 7,
    "special": "Cumbersome 3, Limited Ammo 1, Pierce 1, Vicious 2",
    "features": null
  },
  {
    "type": "Other",
    "name": "TaggeCo CryoBan Projector",
    "source": null,
    "skill": "Heavy",
    "damage": 6,
    "critical": 2,
    "range": "Short",
    "encumbrance": 3,
    "hardPoints": 0,
    "price": 500,
    "rarity": 4,
    "special": "Blast 6, Cumbersome 3, Vicious",
    "features": null
  },
  {
    "type": "Other",
    "name": "Tangle Gun",
    "source": null,
    "skill": "Heavy",
    "damage": 1,
    "critical": 4,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 1,
    "price": 500,
    "rarity": 5,
    "special": "Ensnare 3",
    "features": null
  },
  {
    "type": "Other",
    "name": "Net Gun",
    "source": null,
    "skill": "Heavy",
    "damage": 3,
    "critical": null,
    "range": "Short",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 750,
    "rarity": 5,
    "special": "Ensnare 5",
    "features": null
  },
  {
    "type": "Other",
    "name": "Palandrix AO14 Aranea",
    "source": null,
    "skill": "Heavy",
    "damage": 3,
    "critical": null,
    "range": "Medium",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 775,
    "rarity": 5,
    "special": "Ensnare 5, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Field Sports Model 77 Air Rifle",
    "source": null,
    "skill": "Heavy",
    "damage": 6,
    "critical": null,
    "range": "Long",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 1100,
    "rarity": 6,
    "special": "Pierce 4, Stun Damage",
    "features": null
  },
  {
    "type": "Other",
    "name": "L70 Acid Projector",
    "source": null,
    "skill": "Heavy",
    "damage": 6,
    "critical": 2,
    "range": "Short",
    "encumbrance": 4,
    "hardPoints": 1,
    "price": 1250,
    "rarity": 7,
    "special": "Blast 6, Burn 3, Vicious 1",
    "features": "May activate Burn multiple times on multiple targets hit; 2 Threat or 1 Despair to Burn ally hit by original attack"
  },
  {
    "type": "Other",
    "name": "R88 Supressor Riot Rifle",
    "source": null,
    "skill": "Heavy",
    "damage": 8,
    "critical": null,
    "range": "Medium",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 2000,
    "rarity": 5,
    "special": "Blast 5, Disorient 3, Stun Damage",
    "features": null
  },
  {
    "type": "Other",
    "name": "Stokhli Spray Stick",
    "source": null,
    "skill": "Heavy",
    "damage": 0,
    "critical": null,
    "range": "Long",
    "encumbrance": 4,
    "hardPoints": 0,
    "price": 2500,
    "rarity": 8,
    "special": "Accurate 2, Ensnare 4, Slow-Firing 1, Stun 8",
    "features": null
  },
  {
    "type": "Other",
    "name": "C-88 Fragmentation Missile",
    "source": null,
    "skill": "Gunnery",
    "damage": 12,
    "critical": 4,
    "range": "Extreme",
    "encumbrance": 0,
    "hardPoints": 0,
    "price": 75,
    "rarity": 7,
    "special": "Blast 12, Guided 3",
    "features": null
  },
  {
    "type": "Other",
    "name": "Incendiary Missile",
    "source": null,
    "skill": "Gunnery",
    "damage": 10,
    "critical": 3,
    "range": "Extreme",
    "encumbrance": 0,
    "hardPoints": 0,
    "price": "R 145",
    "rarity": 7,
    "special": "Blast 10, Burn 3, Guided 2",
    "features": "Ammunition for Missile Tube"
  },
  {
    "type": "Other",
    "name": "Plasma Missile",
    "source": null,
    "skill": "Gunnery",
    "damage": 16,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 0,
    "hardPoints": 0,
    "price": "R 160",
    "rarity": 8,
    "special": "Blast 14, Cumbersome 3, Inaccurate 1, Pierce 2",
    "features": "Ammunition for Missile Tube"
  },
  {
    "type": "Other",
    "name": "Concussion Missile",
    "source": null,
    "skill": "Gunnery",
    "damage": 14,
    "critical": 4,
    "range": "Extreme",
    "encumbrance": 0,
    "hardPoints": 0,
    "price": 200,
    "rarity": 8,
    "special": "Blast 10, Concussive 3, Disorient 5, Guided 2",
    "features": "Ammunition for Missile Tube"
  },
  {
    "type": "Other",
    "name": "Greanade Launcher",
    "source": null,
    "skill": "Gunnery",
    "damage": 8,
    "critical": 4,
    "range": "Medium",
    "encumbrance": 5,
    "hardPoints": 3,
    "price": "R1250",
    "rarity": 4,
    "special": "Blast 6, Cumbersome 3, Limited Ammo 6",
    "features": null
  },
  {
    "type": "Other",
    "name": "CZ28 Flamestrike",
    "source": null,
    "skill": "Gunnery",
    "damage": 9,
    "critical": 2,
    "range": "Short",
    "encumbrance": 8,
    "hardPoints": 3,
    "price": "R 2000",
    "rarity": 8,
    "special": "Burn 4, Blast 9, Cumbersome 3, Vicious 2",
    "features": null
  },
  {
    "type": "Other",
    "name": "Flachette Launcher (Anti-Infantry)",
    "source": null,
    "skill": "Gunnery",
    "damage": 8,
    "critical": 3,
    "range": "Medium",
    "encumbrance": 6,
    "hardPoints": 4,
    "price": "R 2500",
    "rarity": 6,
    "special": "Blast 8, Cumbersome 3, Limited Ammo 4, Pierce 6, Prepare 1, Vicious 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Flachette Launcher (Anti-Vehicle)",
    "source": null,
    "skill": "Gunnery",
    "damage": 10,
    "critical": 2,
    "range": "Medium",
    "encumbrance": 6,
    "hardPoints": 4,
    "price": "R 2500",
    "rarity": 6,
    "special": "Breach 2, Cumbersome 3, Limited Ammo 4, Pierce 6, Prepare 1, Vicious 1",
    "features": null
  },
  {
    "type": "Other",
    "name": "Missile Tube",
    "source": null,
    "skill": "Gunnery",
    "damage": 20,
    "critical": 2,
    "range": "Extreme",
    "encumbrance": 7,
    "hardPoints": 4,
    "price": "R 7500",
    "rarity": 8,
    "special": "Blast 10, Cumbersome 3, Guided 3, Breach1, Prepare1, Limited Ammo 6",
    "features": null
  },
  {
    "type": "Explosives",
    "name": "Detonite Charges",
    "source": null,
    "skill": "Mechanics",
    "damage": 15,
    "critical": null,
    "range": "Short",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": 50,
    "rarity": 2,
    "special": "Blast radius = Short",
    "features": "+10 dam for each additional charge"
  },
  {
    "type": "Explosives",
    "name": "Proton Grenade",
    "source": null,
    "skill": "Mechanics",
    "damage": 10,
    "critical": null,
    "range": "Short",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 60,
    "rarity": 4,
    "special": "Blast radius = Short",
    "features": "Each grenade adds 10x(total # of grenades) damage; blast rad. Increase by 1 band per grenade after 1st 5"
  },
  {
    "type": "Explosives",
    "name": "Baradium Charge",
    "source": null,
    "skill": "Mechanics",
    "damage": 3,
    "critical": null,
    "range": "Long",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": "R 750",
    "rarity": 5,
    "special": "Blast radius = Long",
    "features": "Damage is on Planetary Scale; +1 Damage per additional charge; Despair = immidate explosion, +50 to critical roll if Engaged"
  },
  {
    "type": "Explosives",
    "name": "Anti-Personnel Mine",
    "source": null,
    "skill": "Mechanics",
    "damage": 12,
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 0,
    "price": "R 850",
    "rarity": 6,
    "special": "Blast 4, Vicious 4, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Explosives",
    "name": "Anti-Vehicle Mine",
    "source": null,
    "skill": "Mechanics",
    "damage": 25,
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 0,
    "price": "R 1400",
    "rarity": 6,
    "special": "Blast 2, Breach 4, Limited Ammo 1",
    "features": null
  },
  {
    "type": "Brawl Weapon",
    "name": "Brass Knuckles",
    "source": "Cores",
    "skill": "Brawl",
    "damage": "BR+1",
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 25,
    "rarity": 0,
    "special": "Disorient 3",
    "features": null
  },
  {
    "type": "Brawl Weapon",
    "name": "Shock Gloves",
    "source": "Cores",
    "skill": "Brawl",
    "damage": "BR+0",
    "critical": 5,
    "range": "Engaged",
    "encumbrance": 0,
    "hardPoints": 1,
    "price": 300,
    "rarity": 2,
    "special": "Stun 3",
    "features": null
  },
  {
    "type": "Brawl Weapon",
    "name": "Vibroknucklers",
    "source": "DC",
    "skill": "Brawl",
    "damage": "BR+1",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 350,
    "rarity": 4,
    "special": "Pierce 1, Vicious 1",
    "features": null
  },
  {
    "type": "Brawl Weapon",
    "name": "S-1 Vamblade",
    "source": "DC",
    "skill": "Brawl",
    "damage": "BR+1",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 1,
    "price": 500,
    "rarity": 4,
    "special": "Defensive 1 (Sunder, Accurate 1 when used in a pair)",
    "features": null
  },
  {
    "type": "Brawl Weapon",
    "name": "Blast Knuckles",
    "source": "DC",
    "skill": "Brawl",
    "damage": "BR+4",
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": "R 500",
    "rarity": 6,
    "special": "Inaccurate 1",
    "features": null
  },
  {
    "type": "Brawl Weapon",
    "name": "Needle Gloves",
    "source": "DA",
    "skill": "Brawl",
    "damage": "BR+0",
    "critical": 5,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": "R 750",
    "rarity": 8,
    "special": null,
    "features": "Can be used to inject toxins upon successful attack."
  },
  {
    "type": "Brawl Weapon",
    "name": "Refined Cortosis Gauntlets",
    "source": "FDC",
    "skill": "Brawl",
    "damage": "BR+1",
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 2,
    "price": 1000,
    "rarity": 7,
    "special": "Cortosis",
    "features": null
  },
  {
    "type": "Brawl Weapon",
    "name": "Shock Boots",
    "source": "FC",
    "skill": "Brawl",
    "damage": "BR+0",
    "critical": 5,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": 1250,
    "rarity": 5,
    "special": "Disorient 3, Stun 3",
    "features": null
  },
  {
    "type": "Brawl Weapon",
    "name": "Shield Gauntlet",
    "source": "KP",
    "skill": "Brawl",
    "damage": "BR+1",
    "critical": 5,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 1500,
    "rarity": 8,
    "special": "Deflection 2, Stun Damage",
    "features": "Counts as weilding a lightsaber for the Reflect Talent"
  },
  {
    "type": "Brawl Weapon",
    "name": "SVT-300 Stun Cloak",
    "source": "SR",
    "skill": "Brawl",
    "damage": 7,
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": 1500,
    "rarity": 4,
    "special": "Limited Ammo 3, Stun Damage",
    "features": null
  },
  {
    "type": "Brawl Weapon",
    "name": "Backhand Shock Gloves",
    "source": "FH",
    "skill": "Brawl",
    "damage": "BR+1",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 0,
    "hardPoints": 2,
    "price": 2000,
    "rarity": 4,
    "special": "Concussive 1, Stun Damage, Slow-Firing 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Truncheon",
    "source": "Cores",
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 5,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": 15,
    "rarity": 1,
    "special": "Disorient 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Entrenching Tool",
    "source": "DC",
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 20,
    "rarity": 1,
    "special": "Inferior",
    "features": "Threat and Despair will not break this weapon"
  },
  {
    "type": "Melee Weapon",
    "name": "Combat Knife",
    "source": "Cores",
    "skill": "Melee",
    "damage": "BR+1",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 25,
    "rarity": 1,
    "special": null,
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Snap Baton",
    "source": "KP",
    "skill": "Melee",
    "damage": "BR+1",
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 50,
    "rarity": 4,
    "special": "Disorient 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Punch Dagger",
    "source": "FC",
    "skill": "Melee",
    "damage": "BR+1",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 75,
    "rarity": 4,
    "special": "Pierce 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Explorer's Knife",
    "source": "SS",
    "skill": "Melee",
    "damage": "BR+1",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": 100,
    "rarity": 3,
    "special": "Vicious 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Gaffi Stick",
    "source": "EEC",
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 0,
    "price": 100,
    "rarity": 2,
    "special": "Defensive 1, Disorient 3",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Thermal Cutter",
    "source": "NP",
    "skill": "Melee",
    "damage": 4,
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": 125,
    "rarity": 3,
    "special": "Burn 1, Inaccurate 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Electromagnetic-Pulse Disruptor",
    "source": "SM",
    "skill": "Melee",
    "damage": 5,
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 180,
    "rarity": 5,
    "special": "Disorient 1, Ion",
    "features": "+2 setback die to any checks to sabotage electronics; +1 setback die to find this weapon on person"
  },
  {
    "type": "Melee Weapon",
    "name": "Stun Baton",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 6,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": 200,
    "rarity": 4,
    "special": "Disorient 2, Stun Damage",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Vibroknife",
    "source": null,
    "skill": "Melee",
    "damage": "BR+1",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 2,
    "price": 250,
    "rarity": 3,
    "special": "Pierce 2, Vicious 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Blade-breaker",
    "source": null,
    "skill": "Melee",
    "damage": "BR+0",
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 250,
    "rarity": 5,
    "special": "Defensive 2, Pierce 1, Sunder",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Riot Shield",
    "source": null,
    "skill": "Melee",
    "damage": "BR+0",
    "critical": 6,
    "range": "Engaged",
    "encumbrance": 5,
    "hardPoints": 1,
    "price": 300,
    "rarity": 4,
    "special": "Cumbersome 3, Defensive 2, Deflection 2, Disorient 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Corellian Cutlass",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 1,
    "price": 300,
    "rarity": 3,
    "special": "Defensive 1, Vicious 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Electronet",
    "source": null,
    "skill": "Melee",
    "damage": 6,
    "critical": 6,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": 350,
    "rarity": 6,
    "special": "Ensnare 5, Knockdown, Limited Ammo 1, Stun Damage",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Staff of Office",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 2,
    "price": 350,
    "rarity": 6,
    "special": "Defensive 1, Disorient 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Stealth Vibroknife",
    "source": null,
    "skill": "Melee",
    "damage": "BR+1",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 350,
    "rarity": 6,
    "special": "Pierce 1, Vicious 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Drall Flashstick",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": null,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": 375,
    "rarity": 4,
    "special": "Disorient 3, Stun Damage",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Ryyk Blade",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 400,
    "rarity": 8,
    "special": "Cumbersome 3, Defensive 1, Superior",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Sword Cane",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 1,
    "price": 475,
    "rarity": 6,
    "special": "Defensive 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Merr-Sonn Model 14 Stalker",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 490,
    "rarity": 6,
    "special": "Defensive 1, Pierce 2, Vicious 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Force Pike",
    "source": null,
    "skill": "Melee",
    "damage": "BR+3",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 500,
    "rarity": 4,
    "special": "Pierce 2, Stun Setting",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Hand Grinder",
    "source": "SM",
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 5,
    "hardPoints": 4,
    "price": 500,
    "rarity": 3,
    "special": "Cumbersome 3, Prepare 1, Vicious 4",
    "features": "+1 Advantage to Mechancs checks to shape hardened materials"
  },
  {
    "type": "Melee Weapon",
    "name": "Molecular Stiletto",
    "source": null,
    "skill": "Melee",
    "damage": "BR+0",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 1,
    "price": 500,
    "rarity": 5,
    "special": "Pierce 5, Vicious 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Vibro-Machete",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 1,
    "price": 550,
    "rarity": 4,
    "special": "Pierce 1, Sunder, Vicious 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Longeling Whip",
    "source": null,
    "skill": "Melee",
    "damage": "BR+1",
    "critical": 5,
    "range": "Short",
    "encumbrance": 3,
    "hardPoints": 1,
    "price": 600,
    "rarity": 4,
    "special": "Ensnare 1, Stun Damage",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Laserhone Trailbreaker Poleaxe",
    "source": null,
    "skill": "Melee",
    "damage": "BR+3",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 5,
    "hardPoints": 1,
    "price": 610,
    "rarity": 4,
    "special": "Defensive 1, Pierce 2, Unwieldy 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Ceremonial Blade",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 3,
    "price": 650,
    "rarity": 7,
    "special": "Defensive 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "MSQ-12 NanoDagger",
    "source": null,
    "skill": "Melee",
    "damage": "BR+1",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": 700,
    "rarity": 6,
    "special": "Pierce 5, Vicious 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Vibro-Ax",
    "source": null,
    "skill": "Melee",
    "damage": "BR+3",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 3,
    "price": 750,
    "rarity": 5,
    "special": "Pierce 2, Sunder, Vicious 3",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Vibrosword",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 750,
    "rarity": 5,
    "special": "Defensive 1, Pierce 2, Vicious 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Therm-Ax",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 3,
    "price": "R 850",
    "rarity": 5,
    "special": "Burn 2, Sunder, Vicious 1",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Thunderbolt",
    "source": null,
    "skill": "Melee",
    "damage": 5,
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": 875,
    "rarity": 6,
    "special": "Concussive 1, Stun Damage",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Vibro-Greatsword",
    "source": null,
    "skill": "Melee",
    "damage": "BR+3",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 3,
    "price": 900,
    "rarity": 6,
    "special": "Defensive 1, Pierce 2, Vicious 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Huntsman Vibrospear",
    "source": null,
    "skill": "Melee",
    "damage": "BR+3",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 950,
    "rarity": 6,
    "special": "Pierce 2, Vicious 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "SoroSuub Persuader",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 1000,
    "rarity": 4,
    "special": "Concussive 1, Slow-Firing, Stun Setting",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Cortosis Shield",
    "source": null,
    "skill": "Melee",
    "damage": "BR+0",
    "critical": 6,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 0,
    "price": 1000,
    "rarity": 7,
    "special": "Cortosis, Cumbersome 3, Defensive 1, Deflection 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "G9-GP Plulse Drill",
    "source": null,
    "skill": "Melee",
    "damage": 5,
    "critical": 4,
    "range": "Engaged",
    "encumbrance": 5,
    "hardPoints": 2,
    "price": 1100,
    "rarity": 4,
    "special": "Breach 1, Cumbersome 3, Inaccurate 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Vibrorapier",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 2,
    "price": 1200,
    "rarity": 7,
    "special": "Defensive 1, Pierce 5",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Selonian Glaive",
    "source": null,
    "skill": "Melee",
    "damage": "BR+3",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 5,
    "hardPoints": 3,
    "price": 1200,
    "rarity": 7,
    "special": "Defensive 1, Pierce 3",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Mon Calamari Spear Blaster",
    "source": "SR",
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 5,
    "hardPoints": 4,
    "price": 1350,
    "rarity": 5,
    "special": "Pierce 1",
    "features": "Can be used as a blaster as well (see Energy weapons)"
  },
  {
    "type": "Melee Weapon",
    "name": "Mk III Vibrosaw",
    "source": null,
    "skill": "Melee",
    "damage": "BR+4",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 6,
    "hardPoints": 3,
    "price": 1500,
    "rarity": 5,
    "special": "Cumbersome 5, Pierce 2, Sunder, Vicious 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Mon Calamari Energy Lance",
    "source": null,
    "skill": "Melee",
    "damage": "BR+3",
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 1500,
    "rarity": 6,
    "special": "Cumbersome 3 (unless mounted), Pierce 3",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Welding Rod",
    "source": "SM",
    "skill": "Melee",
    "damage": 3,
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 0,
    "price": 1750,
    "rarity": 5,
    "special": "Breach 1, Inaccurate 2",
    "features": "+1 Success to repair drois and vehicles; 1 Despair to Critically Injure wielder"
  },
  {
    "type": "Melee Weapon",
    "name": "Cortosis Sword",
    "source": null,
    "skill": "Melee",
    "damage": "BR+2",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 2,
    "price": 1800,
    "rarity": 7,
    "special": "Cortosis, Cumbersome 3, Defensive 1, Deflection 2",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Refined Cortosis Staff",
    "source": null,
    "skill": "Melee",
    "damage": "BR+3",
    "critical": 5,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 2,
    "price": 2500,
    "rarity": 7,
    "special": "Cortosis",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "J7b Beamdrill",
    "source": null,
    "skill": "Melee",
    "damage": 9,
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 6,
    "hardPoints": 0,
    "price": 3000,
    "rarity": 5,
    "special": "Breach 1, Cumbersome 4, Inaccurate 2, Sunder",
    "features": null
  },
  {
    "type": "Melee Weapon",
    "name": "Electrostaff",
    "source": null,
    "skill": "Melee",
    "damage": "BR+4",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 4,
    "hardPoints": 1,
    "price": 4500,
    "rarity": 6,
    "special": "Cortosis, Cumbersome 3, Defensive 1, Linked 1, Stn Setting, Unwieldy 3",
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Training Stick",
    "source": null,
    "skill": "Lightsaber",
    "damage": "BR+1",
    "critical": 5,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 0,
    "price": 35,
    "rarity": 3,
    "special": "Accurate 1, Disorient 1, Stun Damage",
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Ancient Sword",
    "source": null,
    "skill": "Lightsaber",
    "damage": "BR+2",
    "critical": 3,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 1,
    "price": 400,
    "rarity": 8,
    "special": null,
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Training Lightsaber",
    "source": null,
    "skill": "Lightsaber",
    "damage": 6,
    "critical": null,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 5,
    "price": 400,
    "rarity": 6,
    "special": "Stun Damage",
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Basic Lightsaber Hilt",
    "source": null,
    "skill": "Lightsaber",
    "damage": 0,
    "critical": null,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 5,
    "price": 300,
    "rarity": 5,
    "special": null,
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Shoto Hilt",
    "source": null,
    "skill": "Lightsaber",
    "damage": 0,
    "critical": null,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 3,
    "price": 300,
    "rarity": 6,
    "special": "Accurate 1",
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Double-Bladed Lightsaber Hilt",
    "source": null,
    "skill": "Lightsaber",
    "damage": 0,
    "critical": null,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 4,
    "price": 600,
    "rarity": 6,
    "special": "Linked 1, Unweildy 2",
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Lightsaber Pike Hilt",
    "source": null,
    "skill": "Lightsaber",
    "damage": 0,
    "critical": null,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": 600,
    "rarity": 7,
    "special": "Cumbersome 3, Defense 1",
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Shoto",
    "source": null,
    "skill": "Lightsaber",
    "damage": 4,
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 3,
    "price": "R 9300",
    "rarity": 10,
    "special": "Accurate 1, Breach 1, Sunder",
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Basic Lightsaber",
    "source": null,
    "skill": "Lightsaber",
    "damage": 6,
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 5,
    "price": "R 9300",
    "rarity": 10,
    "special": "Breach 1, Sunder",
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Lightsaber Pike",
    "source": null,
    "skill": "Lightsaber",
    "damage": 6,
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 3,
    "hardPoints": 3,
    "price": "R 9600",
    "rarity": 10,
    "special": "Breach 1, Cumbersome 3, Defensive 1, Sunder",
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Double-Bladed Lightsaber",
    "source": null,
    "skill": "Lightsaber",
    "damage": 6,
    "critical": 2,
    "range": "Engaged",
    "encumbrance": 2,
    "hardPoints": 4,
    "price": "R 10200",
    "rarity": 10,
    "special": "Breach 1, Linked 1, Sunder, Unwieldy 2",
    "features": null
  },
  {
    "type": "Lightsaber",
    "name": "Lightsaber",
    "source": null,
    "skill": "Lightsaber",
    "damage": 10,
    "critical": 1,
    "range": "Engaged",
    "encumbrance": 1,
    "hardPoints": 0,
    "price": "R 10000",
    "rarity": 10,
    "special": "Breach 1, Sunder, Vicious 2",
    "features": null
  }
];